name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
        TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
        TF_VAR_allowed_apple_id: ${{ secrets.ALLOWED_APPLE_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
  
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
  
      - name: Terraform Init
        run: terraform init -reconfigure
  
      - name: Terraform Apply
        run: terraform apply -auto-approve
