name: Terraform Validate

on:
  pull_request:
    paths:
      - 'terraform/**'
      - '.github/workflows/**'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.7

    - name: Init Terraform
      working-directory: terraform
      run: terraform init -backend=false

    - name: Validate Terraform
      working-directory: terraform
      run: terraform validate